Repository GSG-G11/Wasslni, pull requests merged in 2022-04, with the labels that each got.

#3 Create backend file structure
  .eslintrc.json
  .gitignore
  .vscode/settings.json
  package-lock.json
  package.json
  server/controllers/index.ts
  server/database/config/build.sql
  server/database/config/build.ts
  server/database/config/connection.ts
  server/database/config/fakedata.sql
  server/database/quieres/index.ts
  server/middlewares/index.ts
  server/routes/index.ts
  server/utils/index.ts
Labels: Awaiting Review

#6 4 init server
  .eslintrc.json
  .gitignore
  .vscode/settings.json
  package.json
  server/.eslintrc.json
  server/database/config/build.sql
  server/database/config/build.ts
  server/database/config/connection.ts
  server/database/quieres/index.ts
  server/middlewares/index.ts
  server/package-lock.json
  server/package.json
  server/routes/index.ts
  server/src/app.ts
  server/src/controllers/errors/clientError.ts
  server/src/controllers/errors/index.ts
  server/src/controllers/errors/serverError.ts
  server/src/controllers/index.ts
  server/src/database/config/build.sql
  server/src/database/config/build.ts
  server/src/database/config/connection.ts
  server/src/database/config/fakedata.sql
  server/src/database/queries/index.ts
  server/src/index.ts
  server/src/middlewares/index.ts
  server/src/routes/index.ts
  server/src/utils/index.ts
  server/tsconfig.json
  server/utils/index.ts
Labels: Awaiting Review

#7 setup data
  server/package-lock.json
  server/package.json
  server/src/app.ts
  server/src/database/config/build.sql
  server/src/database/config/build.ts
  server/src/database/config/connection.ts
Labels: Awaiting Review

#12 9 signup quiery
  server/package-lock.json
  server/src/database/config/build.sql
  server/src/database/queries/auth/checkPhoneNumber.ts
  server/src/database/queries/auth/index.ts
  server/src/database/queries/auth/signUpDB.ts
Labels: Awaiting Review

#16 handle encrypting password
  server/package-lock.json
  server/package.json
  server/src/utils/password/comparePassword.ts
  server/src/utils/password/hashPassword.ts
  server/src/utils/password/index.ts
Labels: approved

#14 create cloudinary middleware
  server/package-lock.json
  server/package.json
  server/src/database/config/build.sql
  server/src/utils/cloudinary/cloudinary.ts
  server/src/utils/cloudinary/index.ts
  server/tsconfig.json
Labels: approved

#15 handle signup schema
  server/src/utils/errors/CustomError.ts
  server/src/utils/errors/index.ts
  server/src/utils/index.ts
  server/src/utils/validation/index.ts
  server/src/utils/validation/signUpSchema.ts
Labels: approved

#18 convert cloudinary to promise
  server/src/utils/cloudinary/cloudinary.ts
Labels: Awaiting Review

#22 create token async and verify token
  server/package-lock.json
  server/package.json
  server/src/app.ts
  server/src/utils/index.ts
  server/src/utils/jwt/createToken.ts
  server/src/utils/jwt/index.ts
  server/src/utils/jwt/verifyToken.ts
Labels: Awaiting Review

#27 handle signup
  server/src/controllers/index.ts
  server/src/controllers/userControllers/SMS.ts
  server/src/controllers/userControllers/index.ts
  server/src/controllers/userControllers/signUp.ts
  server/src/database/config/build.sql
  server/src/database/queries/auth/checkPhoneNumber.ts
  server/src/database/queries/auth/index.ts
  server/src/database/queries/auth/signUpDB.ts
  server/src/database/queries/index.ts
  server/src/middlewares/checkSeller.ts
  server/src/routes/index.ts
  server/src/utils/cloudinary/cloudinary.ts
  server/src/utils/errors/CustomError.ts
  server/src/utils/index.ts
  server/src/utils/password/index.ts
  server/src/utils/twilio/sendSMS.ts
  server/src/utils/twilio/verifySMS.ts
  server/src/utils/validation/index.ts
  server/src/utils/validation/signUpSchema.ts
  server/src/utils/validation/smsSchema.ts
Labels: Awaiting Review

#28 create login functionality
  server/package-lock.json
  server/src/controllers/index.ts
  server/src/controllers/userControllers/index.ts
  server/src/controllers/userControllers/login.ts
  server/src/controllers/userControllers/signUp.ts
  server/src/database/config/fakedata.sql
  server/src/database/queries/index.ts
  server/src/database/queries/userQuieries/checkPhoneNumber.ts
  server/src/database/queries/userQuieries/index.ts
  server/src/database/queries/userQuieries/signUpDB.ts
  server/src/routes/index.ts
  server/src/utils/index.ts
  server/src/utils/password/comparePassword.ts
  server/src/utils/validation/index.ts
  server/src/utils/validation/loginSchema.ts
Labels: Awaiting Review

#35 refactoring sms & signp
  server/package-lock.json
  server/package.json
  server/src/controllers/userControllers/SMS.ts
  server/src/controllers/userControllers/login.ts
  server/src/controllers/userControllers/signUp.ts
  server/src/routes/index.ts
  server/src/utils/errors/CustomError.ts
  server/src/utils/errors/index.ts
  server/src/utils/index.ts
Labels: Awaiting Review

#42 edit server error
  server/src/controllers/errors/serverError.ts
  server/src/controllers/userControllers/signUp.ts
  server/src/database/queries/userQuieries/signUpDB.ts
Labels: Awaiting Review

#39 create get parcel details functionality and route
  server/src/controllers/index.ts
  server/src/controllers/parcels/index.ts
  server/src/controllers/parcels/parcelDetails.ts
  server/src/database/config/build.sql
  server/src/database/config/fakedata.sql
  server/src/database/queries/index.ts
  server/src/database/queries/parcelsQueries/checkRoleDB.ts
  server/src/database/queries/parcelsQueries/index.ts
  server/src/database/queries/parcelsQueries/parcelDetailsDB.ts
  server/src/routes/index.ts
Labels: Awaiting Review

#45 fix percel controller
  server/src/controllers/parcels/parcelDetails.ts
  server/src/database/queries/index.ts
  server/src/database/queries/parcelsQueries/index.ts
  server/src/database/queries/parcelsQueries/parcelDetailsDB.ts
  server/src/routes/index.ts
Labels: Awaiting Review

#46 post parcel
  server/src/controllers/index.ts
  server/src/controllers/parcels/addParcel.ts
  server/src/controllers/parcels/index.ts
  server/src/controllers/userControllers/login.ts
  server/src/controllers/userControllers/signUp.ts
  server/src/database/config/build.sql
  server/src/database/config/fakedata.sql
  server/src/database/queries/index.ts
  server/src/database/queries/parcelsQueries/addParcelQuery.ts
  server/src/database/queries/parcelsQueries/index.ts
  server/src/routes/index.ts
  server/src/utils/index.ts
  server/src/utils/validation/addParcelSchema.ts
  server/src/utils/validation/index.ts
Labels: Awaiting Review

#47 get All parcels
  server/package-lock.json
  server/src/controllers/index.ts
  server/src/controllers/parcels/getParcels.ts
  server/src/controllers/parcels/index.ts
  server/src/database/queries/index.ts
  server/src/database/queries/parcelsQueries/getParcelsQuery.ts
  server/src/database/queries/parcelsQueries/index.ts
  server/src/routes/index.ts
Labels: Awaiting Review

#48 create delete parcel functionality
  server/src/controllers/index.ts
  server/src/controllers/parcels/deleteParcel.ts
  server/src/controllers/parcels/index.ts
  server/src/controllers/userControllers/login.ts
  server/src/database/config/fakedata.sql
  server/src/database/queries/index.ts
  server/src/database/queries/parcelsQueries/deleteParcelDB.ts
  server/src/database/queries/parcelsQueries/index.ts
  server/src/database/queries/parcelsQueries/parcelDetailsDB.ts
  server/src/routes/index.ts
Labels: approved

#53 fix parcelDetails pass object in parcelDetailsDB
  server/src/controllers/parcels/parcelDetails.ts
Labels: Awaiting Review

#55 Edit profile info route
  server/src/controllers/index.ts
  server/src/controllers/profile/editProfile.ts
  server/src/controllers/profile/getProfile.ts
  server/src/controllers/profile/index.ts
  server/src/database/queries/index.ts
  server/src/database/queries/userQuieries/editProfile.ts
  server/src/database/queries/userQuieries/index.ts
  server/src/routes/index.ts
  server/src/utils/index.ts
  server/src/utils/validation/editProfileInfoSchema.ts
  server/src/utils/validation/index.ts
Labels: Awaiting Review

#60 fetch route from mapbox api and create addRouteQuery
  server/package-lock.json
  server/package.json
  server/src/controllers/parcels/addParcel.ts
  server/src/controllers/parcels/parcelDetails.ts
  server/src/database/config/build.sql
  server/src/database/config/fakedata.sql
  server/src/database/queries/index.ts
  server/src/database/queries/parcelsQueries/parcelDetailsDB.ts
  server/src/database/queries/routeQueries/addRouteQuery.ts
  server/src/database/queries/routeQueries/index.ts
  server/src/index.ts
  server/tsconfig.json
Labels: Awaiting Review

#54 create edit password functionality
  server/src/controllers/index.ts
  server/src/controllers/profile/editPassword.ts
  server/src/controllers/profile/index.ts
  server/src/database/queries/index.ts
  server/src/database/queries/userQuieries/editPasswordDB.ts
  server/src/database/queries/userQuieries/index.ts
  server/src/routes/index.ts
  server/src/utils/index.ts
  server/src/utils/validation/editPasswordSchema.ts
  server/src/utils/validation/index.ts
Labels: Awaiting Review

#56 change status of parcel
  server/src/controllers/index.ts
  server/src/controllers/parcels/changeStatus.ts
  server/src/controllers/parcels/index.ts
  server/src/database/queries/index.ts
  server/src/database/queries/parcelsQueries/changeStatusQuery.ts
  server/src/database/queries/parcelsQueries/index.ts
  server/src/routes/index.ts
Labels: Awaiting Review

#62 solving conflict in userQueries index
  server/src/database/queries/userQuieries/index.ts
Labels: Awaiting Review

#66 Refactoring server side
  server/src/controllers/errors/clientError.ts
  server/src/controllers/errors/serverError.ts
  server/src/controllers/parcels/addParcel.ts
  server/src/controllers/parcels/changeStatus.ts
  server/src/controllers/parcels/deleteParcel.ts
  server/src/controllers/parcels/getParcels.ts
  server/src/controllers/parcels/parcelDetails.ts
  server/src/controllers/profile/editPassword.ts
  server/src/controllers/profile/getProfile.ts
  server/src/controllers/userControllers/SMS.ts
  server/src/controllers/userControllers/login.ts
  server/src/controllers/userControllers/signUp.ts
  server/src/middleware/asyncMiddleware.ts
  server/src/middleware/checkAuth.ts
  server/src/middleware/checkSeller.ts
  server/src/middleware/custom.d.ts
  server/src/routes/index.ts
  server/tsconfig.json
Labels: back-end, approved

#67 setup test
  server/.eslintrc.json
  server/__test__/dataBase.test.ts
  server/__test__/routes.test.ts
  server/babel.config.js
  server/coverage/clover.xml
  server/coverage/coverage-final.json
  server/coverage/lcov-report/base.css
  server/coverage/lcov-report/block-navigation.js
  server/coverage/lcov-report/favicon.png
  server/coverage/lcov-report/index.html
  server/coverage/lcov-report/prettify.css
  server/coverage/lcov-report/prettify.js
  server/coverage/lcov-report/sort-arrow-sprite.png
  server/coverage/lcov-report/sorter.js
  server/coverage/lcov.info
  server/jest.config.js
  server/package-lock.json
  server/package.json
  server/src/database/config/build.ts
  server/src/routes/index.ts
  server/tsconfig.json
Labels: Awaiting Review

#69 test routes
  server/__test__/dataBase.test.ts
  server/__test__/routes.test.ts
  server/coverage/clover.xml
  server/coverage/coverage-final.json
  server/coverage/lcov-report/base.css
  server/coverage/lcov-report/block-navigation.js
  server/coverage/lcov-report/favicon.png
  server/coverage/lcov-report/index.html
  server/coverage/lcov-report/prettify.css
  server/coverage/lcov-report/prettify.js
  server/coverage/lcov-report/sort-arrow-sprite.png
  server/coverage/lcov-report/sorter.js
  server/coverage/lcov.info
  server/package-lock.json
  server/src/database/config/build.ts
Labels: Awaiting Review

#71 refactoring in routes
  server/src/middleware/checkAuth.ts
  server/src/middleware/checkSeller.ts
  server/src/middleware/custom.d.ts
  server/src/routes/authRouter.ts
  server/src/routes/index.ts
  server/src/routes/parcelRouter.ts
  server/src/routes/profileRouter.ts
Labels: Awaiting Review

#74 add created_at in parcel tabel
  server/src/database/config/build.sql
  server/src/database/config/fakedata.sql
Labels: approved

#76 create file structure
  client/.eslintrc.json
  client/.gitignore
  client/package-lock.json
  client/package.json
  client/public/favicon.ico
  client/public/index.html
  client/src/App.css
  client/src/App.js
  client/src/components/Card/Card.css
  client/src/components/Card/Card.jsx
  client/src/components/Form/ErrorMsg/ErrorMsg.css
  client/src/components/Form/ErrorMsg/ErrorMsg.jsx
  client/src/components/Form/Form.css
  client/src/components/Form/Form.jsx
  client/src/components/Form/index.js
  client/src/components/Map/Map.css
  client/src/components/Map/Map.jsx
  client/src/components/Property/Property.css
  client/src/components/Property/Property.jsx
  client/src/components/SideBar/SideBar.css
  client/src/components/SideBar/SideBar.jsx
  client/src/components/UI/Button/Button.css
  client/src/components/UI/Button/Button.jsx
  client/src/components/UI/Image/Image.css
  client/src/components/UI/Image/Image.jsx
  client/src/components/UI/Input/Input.css
  client/src/components/UI/Input/Input.jsx
  client/src/components/UI/Loader/Loader.css
  client/src/components/UI/Loader/Loader.jsx
  client/src/components/UI/Logo/Logo.css
  client/src/components/UI/Logo/Logo.jsx
  client/src/components/UI/Title/Title.css
  client/src/components/UI/Title/Title.jsx
  client/src/components/UI/index.js
  client/src/components/index.js
  client/src/index.css
  client/src/index.js
  client/src/pages/AddParcel/AddParcel.css
  client/src/pages/AddParcel/AddParcel.jsx
  client/src/pages/EditPassword/EditPassword.css
  client/src/pages/EditPassword/EditPassword.jsx
  client/src/pages/EditProfile/EditProfile.css
  client/src/pages/EditProfile/EditProfile.jsx
  client/src/pages/ErrorPage/ErrorPage.css
  client/src/pages/ErrorPage/ErrorPage.jsx
  client/src/pages/Home/Home.css
  client/src/pages/Home/Home.jsx
  client/src/pages/Login/Login.css
  client/src/pages/Login/Login.jsx
  client/src/pages/ParcelDetails/ParcelDetails.css
  client/src/pages/ParcelDetails/ParcelDetails.jsx
  client/src/pages/Parcels/Parcels.css
  client/src/pages/Parcels/Parcels.jsx
  client/src/pages/Profile/Profile.css
  client/src/pages/Profile/Profile.jsx
  client/src/pages/SMS/SMS.css
  client/src/pages/SMS/SMS.jsx
  client/src/pages/Signup/Signup.css
  client/src/pages/Signup/Signup.jsx
  client/src/pages/index.js
Labels: Awaiting Review

#78 set up custom boostrap
  client/.eslintrc.json
  client/package-lock.json
  client/package.json
  client/public/index.html
  client/src/App.css
  client/src/App.js
  client/src/index.css
  client/src/index.js
  client/src/scss/custom.scss
Labels: Awaiting Review

#87 79 create title and button component
  client/package-lock.json
  client/package.json
  client/src/components/UI/Button/Button.jsx
  client/src/components/UI/Title/Title.jsx
Labels: approved

#86 create image component
  client/package-lock.json
  client/src/components/UI/Image/Image.jsx
Labels: Awaiting Review

#83 create form component
  client/src/components/Form/Form.jsx
  client/src/components/Form/index.js
Labels: Awaiting Review

#85 Create signUp & login & sms validation
  client/src/utils/index.js
  client/src/utils/validation/index.js
  client/src/utils/validation/userValidation/index.js
  client/src/utils/validation/userValidation/loginValidation.js
  client/src/utils/validation/userValidation/signupValidation.js
  client/src/utils/validation/userValidation/smsValidation.js
Labels: Awaiting Review

#88 create formik field input
  client/.eslintrc.json
  client/package-lock.json
  client/package.json
  client/public/index.html
  client/src/components/Form/ErrorMsg/ErrorMsg.jsx
  client/src/components/UI/Input/Input.css
  client/src/components/UI/Input/Input.jsx
  client/src/scss/custom.scss
Labels: approved

#104 style floating label input
  client/public/index.html
  client/src/components/UI/Input/Input.css
  client/src/components/UI/Input/Input.jsx
  client/src/index.css
Labels: Awaiting Review

#106 create user context provider
  client/src/context/userContext.js
  client/src/context/userProvider.jsx
  client/src/index.js
Labels: approved

#99 create property component
  client/src/components/Property/Property.css
  client/src/components/Property/Property.jsx
  client/src/components/SideBar/SideBar.jsx
Labels: Awaiting Review

#94 create loader component
  client/src/components/UI/Loader/Loader.jsx
  client/src/scss/custom.scss
Labels: approved

#100 create aside component
  client/package-lock.json
  client/package.json
  client/src/components/SideBar/SideBar.jsx
  client/src/utils/index.js
  client/src/utils/staticData/index.jsx
  client/src/utils/staticData/staticData.jsx
Labels: Awaiting Review

#93 create base64 functionality
  client/src/components/UI/Input/Input.jsx
  client/src/components/UI/index.js
  client/src/utils/getBase64/getBase64Image.jsx
  client/src/utils/getBase64/index.js
  client/src/utils/index.js
Labels: approved

#111 107 sms page
  client/package-lock.json
  client/package.json
  client/src/App.js
  client/src/assets/sms.jpg
  client/src/assets/smsPage.png
  client/src/components/Form/Form.jsx
  client/src/components/Form/index.js
  client/src/components/Form/submitButton/SubmitButton.jsx
  client/src/components/Form/submitButton/index.js
  client/src/components/UI/Image/Image.jsx
  client/src/components/UI/Input/Input.jsx
  client/src/components/UI/Logo/Logo.css
  client/src/components/UI/Logo/Logo.jsx
  client/src/components/UI/index.js
  client/src/components/index.js
  client/src/index.css
  client/src/pages/SMS/SMS.css
  client/src/pages/SMS/SMS.jsx
  client/src/scss/custom.scss
  client/src/utils/index.js
  client/src/utils/staticData/staticData.jsx
  client/src/utils/validation/userValidation/loginValidation.js
  client/src/utils/validation/userValidation/signupValidation.js
  client/src/utils/validation/userValidation/smsValidation.js
Labels: approved

#114 create login page
  client/src/pages/Login/Login.jsx
  client/src/pages/index.js
  client/src/utils/validation/userValidation/loginValidation.js
Labels: approved
