Repository GSG-G11/Wasslni, pull requests merged in 2022-05, with the labels that each got.

#122 create logout route
  server/src/controllers/index.ts
  server/src/controllers/userControllers/index.ts
  server/src/controllers/userControllers/logout.ts
  server/src/routes/authRouter.ts
Labels: Awaiting Review

#127 edit get parcels route
  server/src/controllers/parcels/getParcels.ts
Labels: approved

#134 edit cookie payload
  server/src/controllers/profile/editProfile.ts
  server/src/controllers/userControllers/login.ts
  server/src/controllers/userControllers/signUp.ts
Labels: approved

#132 create toast component
  client/src/App.js
  client/src/components/Toast/Toast.css
  client/src/components/Toast/Toast.jsx
  client/src/components/index.js
  client/src/pages/AddParcel/AddParcel.css
  client/src/pages/AddParcel/AddParcel.jsx
Labels: Awaiting Review

#136 decode token and check user auth
  client/.eslintrc.json
  client/package-lock.json
  client/package.json
  client/src/context/userProvider.jsx
  client/src/index.js
  client/src/pages/index.js
  client/src/utils/index.js
  client/src/utils/userInfo/getUserInfo.js
  server/src/controllers/profile/editProfile.ts
  server/src/controllers/userControllers/login.ts
  server/src/controllers/userControllers/signUp.ts
Labels: approved

#138 handle routes in app
  client/src/App.js
  client/src/components/SideBar/SideBar.jsx
  client/src/components/index.js
  client/src/context/userProvider.jsx
  client/src/pages/AddParcel/AddParcel.jsx
  client/src/pages/EditPassword/EditPassword.jsx
  client/src/pages/EditProfile/EditProfile.jsx
  client/src/pages/ParcelDetails/ParcelDetails.jsx
  client/src/pages/Parcels/Parcels.jsx
  client/src/pages/Profile/Profile.jsx
  client/src/pages/Signup/Signup.jsx
  client/src/pages/index.js
  client/src/utils/staticData/staticData.jsx
  package-lock.json
Labels: Awaiting Review

#147 changes on edit profile route
  server/src/controllers/profile/editProfile.ts
  server/src/utils/validation/editProfileInfoSchema.ts
Labels: approved

#150 fix parcelDetailsDB
  server/src/database/queries/parcelsQueries/parcelDetailsDB.ts
Labels: Awaiting Review, back-end

#142 get user information after login successfully
  client/src/pages/Login/Login.jsx
Labels: Awaiting Review

#151 149 Create' edit profile' page
  client/.eslintrc.json
  client/src/pages/EditProfile/EditProfile.css
  client/src/pages/EditProfile/EditProfile.jsx
  client/src/utils/index.js
  client/src/utils/staticData/staticData.jsx
  client/src/utils/validation/index.js
  client/src/utils/validation/userValidation/editPasswordValidation.js
  client/src/utils/validation/userValidation/editProfileValidation.js
  client/src/utils/validation/userValidation/index.js
Labels: Awaiting Review

#154 render new parcel
  client/src/components/index.js
  client/src/pages/AddParcel/AddParcel.jsx
  client/src/pages/Parcels/Parcels.jsx
  server/src/controllers/parcels/addParcel.ts
Labels: Awaiting Review

#156 handle logout
  client/src/components/SideBar/SideBar.jsx
Labels: Awaiting Review

#144 create sign up page
  client/.eslintrc.json
  client/package-lock.json
  client/src/components/UI/Select/Select.css
  client/src/components/UI/Select/Select.jsx
  client/src/pages/Signup/Signup.css
  client/src/pages/Signup/Signup.jsx
  client/src/utils/getBase64/getBase64Image.jsx
  client/src/utils/validation/userValidation/signupValidation.js
Labels: Awaiting Review

#131 create profile page
  client/src/components/SideBar/SideBar.css
  client/src/components/SideBar/SideBar.jsx
  client/src/pages/Parcels/Parcels.jsx
  client/src/pages/Profile/Profile.css
  client/src/pages/Profile/Profile.jsx
  client/src/pages/index.js
Labels: Awaiting Review

#160 handle delete parcel
  client/src/pages/ParcelDetails/ParcelDetails.jsx
Labels: Awaiting Review

#162 edit logout
  client/.eslintrc.json
  client/src/components/SideBar/SideBar.jsx
Labels: Awaiting Review

#159 157 refactor http request
  client/package-lock.json
  client/package.json
  client/src/App.js
  client/src/pages/EditProfile/EditProfile.jsx
  client/src/services/http.js
Labels: approved

#164 refactor http requests
  client/package-lock.json
  client/src/App.js
  client/src/components/SideBar/SideBar.jsx
  client/src/pages/AddParcel/AddParcel.jsx
  client/src/pages/EditPassword/EditPassword.css
  client/src/pages/EditPassword/EditPassword.jsx
  client/src/pages/EditProfile/EditProfile.jsx
  client/src/pages/Login/Login.jsx
  client/src/pages/ParcelDetails/ParcelDetails.jsx
  client/src/pages/Parcels/Parcels.jsx
  client/src/pages/Profile/Profile.jsx
  client/src/pages/Signup/Signup.jsx
  client/src/pages/index.js
Labels: approved

#168 init npm and set up for deploy
  package-lock.json
  package.json
  server/src/app.ts
Labels: Done

#172 fix delivery price
  server/.eslintrc.json
  server/src/controllers/parcels/addParcel.ts
Labels: Awaiting Review

#170 fix add parcel
  client/src/pages/AddParcel/AddParcel.jsx
Labels: Awaiting Review

#174 install ts as dependeny
  server/package-lock.json
  server/package.json
Labels: Done

#176 edit tsconfig.json
  server/tsconfig.json
Labels: Done

#177 edit tsconfig.json
  server/tsconfig.json
Labels: Done

#178 fix eslint deploy issue
  client/package-lock.json
  client/package.json
Labels: Done

#179 fix eslint config
  client/package.json
Labels: Done

#181 fix connection db
  server/src/database/config/connection.ts
Labels: Done

#183 fix rendering map at heroku
  client/src/components/Map/Map.jsx
Labels: Done

#185 set user pohne number after signup
  client/src/pages/Signup/Signup.jsx
Labels: Done

#187 edit parcel validation schema
  client/src/utils/validation/ParcelValidation/addParcelValidation.js
Labels: Done

#188 create readme file
  README.md
Labels: Awaiting Review

#189 1 fix readme
  README.md
Labels: Done

#191 Add animation & Fix responsive
  client/.eslintrc.json
  client/src/App.js
  client/src/index.css
  client/src/pages/Home/Home.css
  client/src/pages/Login/Login.css
  client/src/pages/Parcels/Parcels.css
  client/src/pages/Parcels/Parcels.jsx
  client/src/pages/Profile/Profile.css
  client/src/pages/SMS/SMS.css
  client/src/pages/Signup/Signup.css
  client/src/utils/validation/userValidation/signupValidation.js
Labels: Awaiting Review

#193 fix rendering profile page
  client/src/pages/Login/Login.jsx
  client/src/pages/Profile/Profile.jsx
  client/src/pages/SMS/SMS.jsx
Labels: approved

#195 fix an error in profile page
  client/src/pages/Profile/Profile.jsx
Labels: approved

#197 fix logo and buttom in eidtProfile
  client/.eslintrc.json
  client/src/components/UI/Logo/Logo.css
  client/src/components/UI/Logo/Logo.jsx
  client/src/pages/EditProfile/EditProfile.css
Labels: Awaiting Review

#199 fix the request size
  client/.eslintrc.json
  server/src/app.ts
Labels: approved
